[project]
name = "cadevil-webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-bolt>=0.10.0",
    "django-stubs>=6.1.0",
    "pyrefly>=1.2.0",
]

[project.entry-points."cadevil.plugins"]
"cadevil.example.editor" = "example_plugin:plugin_manifest"
"cadevil.rust-example.editor" = "rust_example_plugin:plugin_manifest"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
