"""Adapt Bolt requests for Django forms/templates without Django URL dispatch."""
import io
from functools import wraps
from urllib.parse import urlencode

from asgiref.sync import sync_to_async

from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.core.handlers.wsgi import WSGIRequest
from django.http import Http404, QueryDict, StreamingHttpResponse
from django.middleware.csrf import CsrfViewMiddleware
from django_bolt.exceptions import HTTPException
from django_bolt.responses import StreamingResponse


def form_request(request):
    # WSGIRequest supplies Django's standard multipart parser, upload limits,
    # repeated form fields and QueryDict semantics. Bolt remains the router.
    body = request.body or b''
    environ = dict(request.META)
    environ.update({
        'REQUEST_METHOD': request.method, 'PATH_INFO': request.path,
        'SCRIPT_NAME': '', 'SERVER_NAME': environ.get('SERVER_NAME', 'localhost'),
        'SERVER_PORT': environ.get('SERVER_PORT', '80'),
        'wsgi.url_scheme': 'https' if request.build_absolute_uri().startswith('https:') else 'http',
        'wsgi.input': io.BytesIO(body), 'CONTENT_LENGTH': str(len(body)),
    })
    adapted = WSGIRequest(environ)
    # Share META so the outer Bolt Django middleware can issue the CSRF cookie
    # generated by templates, and preserve session/auth/message context.
    adapted.META = request.META
    adapted.GET = QueryDict(urlencode(request.query, doseq=True))
    adapted.params = request.params
    adapted.user = request.user
    for key in ('session', '_messages'):
        if key in request.state:
            setattr(adapted, key, request.state[key])
    return adapted


def page_endpoint(handler):
    def invoke(request, *args, **kwargs):
        adapted = form_request(request)
        try:
            # Bolt 0.11's middleware adapter does not populate multipart POST.
            # Defer its CSRF process_view check until the real form is parsed.
            # This is the standard Django check (cookie/token/origin/referer).
            rejected = CsrfViewMiddleware(lambda _: None).process_view(adapted, handler, args, kwargs)
            if rejected is not None:
                return rejected
            response = handler(adapted, *args, **kwargs)
            if isinstance(response, StreamingHttpResponse):
                def chunks():
                    try:
                        yield from response.streaming_content
                    finally:
                        response.close()
                return StreamingResponse(chunks(), status_code=response.status_code,
                    media_type=response.get('Content-Type', 'application/octet-stream'),
                    headers=dict(response.items()))
            return response
        except Http404 as error:
            raise HTTPException(404, str(error)) from error
        except PermissionDenied as error:
            raise HTTPException(403, str(error)) from error
        except SuspiciousOperation as error:
            raise HTTPException(400, str(error)) from error
        finally:
            adapted.close()

    @wraps(handler)
    async def wrapped(request, *args, **kwargs):
        # The reused forms, storage, templates and transactions are synchronous.
        # Keep them off Bolt's async middleware loop, including lazy session auth.
        return await sync_to_async(invoke, thread_sensitive=True)(request, *args, **kwargs)

    # Only the early middleware check is deferred. The check above is mandatory
    # on every routed request and does not call an exempt callback.
    wrapped.csrf_exempt = True
    return wrapped
