material_name_translation_dict: dict[str, str] = {
    "Belag, Fliesen": "Belag Fliesen",
    "Belag, Parkett": "Parkett",
    # Beton
    "Beton, Stahlbeton": "Stahlbeton",
    "Beton, Stahlbeton Wand": "Stahlbeton",
    "Beton, Stahlbeton Decke": "Stahlbeton",
    "Beton, Fertigteil": "Beton Fertigteil",
    "Boden, Pflaster": "Boden Pflaster",
    "Dränschicht": "Dränschicht",
    # Dämmung
    "Dämmung, hart XPS": "Dämmung hart XPS",
    "Dämmung, Holzwolledämmplatte (1)": "Dämmung Holzwolledämmplatte",
    "Dämmung, Holzwolledämmplatte": "Dämmung Holzwolledämmplatte",
    "Estrich": "Estrich",
    "Holz, Holzwerkstoff": "Holzwerkstoff",
    "Dämmung, weich Zellulose (1)": "Dämmung weich Zellulose",
    "Dämmung, weich Zellulose": "Dämmung weich Zellulose",
    "Dämmung, Mineralwolle": "Dämmung Mineralwolle",
    "Dämmung, weich Mineralwolle (1)": "Dämmung weich Mineralwolle",
    "Dämmung, weich Mineralwolle IW02": "Dämmung weich Mineralwolle",
    "Dämmung, weich Mineralwolle IW03": "Dämmung weich Mineralwolle",
    "Dämmung, weich Mineralwolle": "Dämmung weich Mineralwolle",
    "Dämmung, Trittschall": "Trittschalldämmung",
    "Dämmung, hart EPS": "Dämmung hart EPS",
    "Gipskarton (1)": "Gipskarton",
    "Gipskarton": "Gipskarton",
    "Glas, Normalglas": "Glas Normalglass",
    # Holz
    "Holz, Bauholz": "Holz Lattung/Bauholz",
    "Holz, Lattung": "Holz Lattung/Bauholz",
    "Holz, Brettschichtholz HOHE PRIO": "Brettschichtholz",
    "Holz, Brettschichtholz": "Brettschichtholz",
    "Holz, OSB (1)": "Holz OSB",
    "Holz, OSB": "Holz OSB",
    "Dämmung, weich Glaswolle (1)": "Dämmung weich Mineralwolle",
    "Dämmung, hart Mineralwolle (1)": "Dämmung hart Mineralwolle",
    "Dämmung, hart Mineralwolle": "Dämmung hart Mineralwolle",
    "Metall,Blech Grau": "Metall Blech Grau",
    "Metall, Stahl": "Stahl",
    "Maschendrat": "Maschendrat",
    "Sperrschicht 2": "Sperrschicht",
    "Sperrschicht": "Sperrschicht",
    "Sperrschicht, Folie (1)": "Sperrschicht Folie",
    "Sperrschicht, Folie": "Sperrschicht Folie",
    "FOLIE, PAE FOLIE": "Sperrschicht Folie",
    "Verputz, Kunstharz": "Kunstharzputz",
    "Verputz, Gips": "Verputz Gips",
    "Verputz, Kalk (1)": "Verputz Kalk",
    "Verputz, Kalk HOLZ Fasade": "Verputz Kalk",
}
