# Generated by Django 5.2.17 on 2026-10-04 07:27

import apps.plugins.bim_model_manager.django.uploads
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadevilDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.plugins.bim_model_manager.django.uploads.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('csv', 'xlsx')), apps.plugins.bim_model_manager.django.uploads.validate_config_upload_size])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='archicad_eval_config_file', to='bim_model_manager.configupload')),
            ],
        ),
        migrations.CreateModel(
            name='EpwUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.plugins.bim_model_manager.django.uploads.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('epw',))])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epw_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('description', 'uploaded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BuildingMetrics',
            fields=[
                ('assessment_report', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grundstuecksfläche', models.FloatField(default=0.0, verbose_name='GF')),
                ('grundstuecksfläche_unit', models.CharField(default='m2', max_length=10)),
                ('bebaute_fläche', models.FloatField(default=0.0, verbose_name='BF')),
                ('bebaute_fläche_unit', models.CharField(default='m2', max_length=10)),
                ('unbebaute_fläche', models.FloatField(default=0.0, verbose_name='UF')),
                ('unbebaute_fläche_unit', models.CharField(default='m2', max_length=10)),
                ('brutto_rauminhalt', models.FloatField(default=0.0, verbose_name='BRI')),
                ('brutto_rauminhalt_unit', models.CharField(default='m3', max_length=10)),
                ('brutto_grundfläche', models.FloatField(default=0.0, verbose_name='BGF')),
                ('brutto_grundfläche_unit', models.CharField(default='m2', max_length=10)),
                ('konstruktions_grundfläche', models.FloatField(default=0.0, verbose_name='KGF')),
                ('konstruktions_grundfläche_unit', models.CharField(default='m2', max_length=10)),
                ('netto_raumfläche', models.FloatField(default=0.0, verbose_name='NRF')),
                ('netto_raumfläche_unit', models.CharField(default='m2', max_length=10)),
                ('bgf_bf_ratio', models.FloatField(default=0.0, verbose_name='BGF/BF')),
                ('bri_bgf_ratio', models.FloatField(default=0.0, verbose_name='BRI/BGF')),
                ('fassadenflaeche', models.FloatField(default=0.0, verbose_name='Facade Area')),
                ('fassadenflaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fassaden_oeffnungsflaeche', models.FloatField(default=0.0, verbose_name='Facade Opening Area')),
                ('fassaden_oeffnungsflaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fassaden_opake_flaeche', models.FloatField(default=0.0, verbose_name='Opaque Facade Area')),
                ('fassaden_opake_flaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fenster_wand_verhaeltnis', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Window-to-Wall Ratio')),
                ('stockwerke', models.FloatField(default=0.0, verbose_name='Stockwerke')),
                ('energie_bewertung', models.CharField(default='Unknown', max_length=50, verbose_name='Energy Rating')),
                ('energy_status', models.CharField(choices=[('not_run', 'Not run'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='not_run', max_length=20)),
                ('annual_site_energy_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annual_electricity_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annual_natural_gas_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_use_intensity_kwh_m2_year', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_error', models.TextField(blank=True, default='')),
                ('energy_assumptions', models.TextField(blank=True, default='')),
                ('energy_weather_file', models.CharField(blank=True, default='', max_length=255)),
                ('openstudio_version', models.CharField(blank=True, default='', max_length=50)),
                ('energy_simulated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_metrics', to='bim_model_manager.cadevildocument')),
                ('energy_weather_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_metrics', to='bim_model_manager.epwupload')),
            ],
            options={
                'verbose_name': 'Gebäude Kenndaten',
                'verbose_name_plural': 'Gebäude Kenndaten',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.plugins.bim_model_manager.django.uploads.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ifc',)), apps.plugins.bim_model_manager.django.uploads.validate_model_upload_size])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cadevildocument',
            name='upload',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_file_upload', to='bim_model_manager.fileupload'),
        ),
        migrations.CreateModel(
            name='MaterialProperties',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('global_brutto_price', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('local_brutto_price', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('local_netto_price', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('area', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('length', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mass', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_a1_a3', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_a1_a3', models.FloatField(blank=True, default=None, null=True)),
                ('ap_ml_a1_a3', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_a1_a3_b4', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_a1_a3_b4', models.FloatField(blank=True, default=None, null=True)),
                ('ap_ml_a1_a3_b4', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_lz', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_lz', models.FloatField(blank=True, default=None, null=True)),
                ('ap_ml_lz', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recyclable_mass', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('waste_mass', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_properties', to='bim_model_manager.cadevildocument')),
            ],
            options={
                'verbose_name_plural': 'Material properties',
            },
        ),
        migrations.CreateModel(
            name='ModelConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to=apps.plugins.bim_model_manager.django.uploads.cityjson_source_path)),
                ('source_sha256', models.CharField(max_length=64)),
                ('output_sha256', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='bim_model_manager.fileupload')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=22)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('source', models.CharField(choices=[('manual', 'Owner-set location'), ('cityjson_geometry', 'CityJSON geometry')], default='manual', max_length=24)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_locations', to='bim_model_manager.fileupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('upload', 'guid'), name='unique_upload_building_location')],
            },
        ),
    ]
