# Generated by Django 5.2.17 on 2026-08-24 23:29

import apps.shared.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadevilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can use moderation tools.', verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='is superuser')),
                ('view_hidden', models.BooleanField(default=False, help_text='Designates whether this user can view hidden content.', verbose_name='view hidden')),
                ('active_calculations', models.IntegerField(default=0, help_text='Number of currently active calculations.', verbose_name='active calculations')),
                ('max_calculations', models.IntegerField(default=1, help_text='Number of currently active calculations.', verbose_name='maximum concurrent active calculations')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto')], default='auto', help_text='Preferred theme for the user interface.', max_length=10, verbose_name='theme')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'library_cadeviluser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CadevilDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archicad_eval_document',
            },
        ),
        migrations.CreateModel(
            name='ConfigUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.shared.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('csv', 'xlsx')), apps.shared.models.validate_config_upload_size])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archicad_eval_config_uploads',
            },
        ),
        migrations.CreateModel(
            name='CalculationConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='archicad_eval_config_file', to='shared.configupload')),
            ],
            options={
                'db_table': 'archicad_eval_calculation_configs',
            },
        ),
        migrations.CreateModel(
            name='EpwUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.shared.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('epw',))])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epw_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archicad_eval_epw_uploads',
                'ordering': ('description', 'uploaded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BuildingMetrics',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grundstuecksfläche', models.FloatField(default=0.0, verbose_name='GF')),
                ('grundstuecksfläche_unit', models.CharField(default='m2', max_length=10)),
                ('bebaute_fläche', models.FloatField(default=0.0, verbose_name='BF')),
                ('bebaute_fläche_unit', models.CharField(default='m2', max_length=10)),
                ('unbebaute_fläche', models.FloatField(default=0.0, verbose_name='UF')),
                ('unbebaute_fläche_unit', models.CharField(default='m2', max_length=10)),
                ('brutto_rauminhalt', models.FloatField(default=0.0, verbose_name='BRI')),
                ('brutto_rauminhalt_unit', models.CharField(default='m3', max_length=10)),
                ('brutto_grundfläche', models.FloatField(default=0.0, verbose_name='BGF')),
                ('brutto_grundfläche_unit', models.CharField(default='m2', max_length=10)),
                ('konstruktions_grundfläche', models.FloatField(default=0.0, verbose_name='KGF')),
                ('konstruktions_grundfläche_unit', models.CharField(default='m2', max_length=10)),
                ('netto_raumfläche', models.FloatField(default=0.0, verbose_name='NRF')),
                ('netto_raumfläche_unit', models.CharField(default='m2', max_length=10)),
                ('bgf_bf_ratio', models.FloatField(default=0.0, verbose_name='BGF/BF')),
                ('bri_bgf_ratio', models.FloatField(default=0.0, verbose_name='BRI/BGF')),
                ('fassadenflaeche', models.FloatField(default=0.0, verbose_name='Facade Area')),
                ('fassadenflaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fassaden_oeffnungsflaeche', models.FloatField(default=0.0, verbose_name='Facade Opening Area')),
                ('fassaden_oeffnungsflaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fassaden_opake_flaeche', models.FloatField(default=0.0, verbose_name='Opaque Facade Area')),
                ('fassaden_opake_flaeche_unit', models.CharField(default='m2', max_length=10)),
                ('fenster_wand_verhaeltnis', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Window-to-Wall Ratio')),
                ('stockwerke', models.FloatField(default=0.0, verbose_name='Stockwerke')),
                ('energie_bewertung', models.CharField(default='Unknown', max_length=50, verbose_name='Energy Rating')),
                ('energy_status', models.CharField(choices=[('not_run', 'Not run'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='not_run', max_length=20)),
                ('annual_site_energy_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annual_electricity_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annual_natural_gas_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_use_intensity_kwh_m2_year', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_error', models.TextField(blank=True, default='')),
                ('energy_assumptions', models.TextField(blank=True, default='')),
                ('energy_weather_file', models.CharField(blank=True, default='', max_length=255)),
                ('openstudio_version', models.CharField(blank=True, default='', max_length=50)),
                ('energy_simulated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_metrics', to='shared.cadevildocument')),
                ('energy_weather_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_metrics', to='shared.epwupload')),
            ],
            options={
                'verbose_name': 'Gebäude Kenndaten',
                'verbose_name_plural': 'Gebäude Kenndaten',
                'db_table': 'building_metrics',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=apps.shared.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ifc',)), apps.shared.models.validate_model_upload_size])),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archicad_eval_uploads',
            },
        ),
        migrations.AddField(
            model_name='cadevildocument',
            name='upload',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_file_upload', to='shared.fileupload'),
        ),
        migrations.AddField(
            model_name='cadeviluser',
            name='uploads',
            field=models.ManyToManyField(blank=True, related_name='file_upload', to='shared.fileupload'),
        ),
        migrations.CreateModel(
            name='MaterialProperties',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('global_brutto_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('local_brutto_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('local_netto_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('area', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('length', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mass', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_a1_a3', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_a1_a3', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ap_ml_a1_a3', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_a1_a3_b4', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_a1_a3_b4', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ap_ml_a1_a3_b4', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('penrt_ml_lz', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gwp_ml_lz', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ap_ml_lz', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recyclable_mass', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('waste_mass', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_properties', to='shared.cadevildocument')),
            ],
            options={
                'verbose_name_plural': 'Material properties',
                'db_table': 'material_properties',
            },
        ),
    ]
