# Generated by Django 5.2.17 on 2026-08-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeviluser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('auto', 'Auto'), ('dark', 'Dark')], default='auto', help_text='Preferred theme for the user interface.', max_length=10, verbose_name='theme'),
        ),
    ]
