# Generated by Django 5.2.17 on 2026-10-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_cadeviluser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeviluser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto')], default='auto', help_text='Preferred theme for the user interface.', max_length=10, verbose_name='theme'),
        ),
    ]
