# Generated by Django 5.2.17 on 2026-10-03 11:49

import apps.shared.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_application_log_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to=apps.shared.models.cityjson_source_path)),
                ('source_sha256', models.CharField(max_length=64)),
                ('output_sha256', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='shared.fileupload')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=22)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('source', models.CharField(choices=[('manual', 'Owner-set location'), ('cityjson_geometry', 'CityJSON geometry')], default='manual', max_length=24)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_locations', to='shared.fileupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('upload', 'guid'), name='unique_upload_building_location')],
            },
        ),
    ]
