[package]
name = "example-plugin-builder"
version = "0.1.0"
edition = "2021"
publish = false
build = false
autobins = false

[lib]
name = "example_plugin"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "build-wasm"
path = "build.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
