# Generated by Django 5.1.3 on 2024-12-31 13:30

import django.db.models.deletion
import model_manager.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_manager', '0002_alter_materialproperties_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigUpload',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('document', models.FileField(upload_to=model_manager.models.user_directory_path)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archicad_eval_config_uploads',
            },
        ),
        migrations.CreateModel(
            name='CalculationConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('config', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                             related_name='archicad_eval_config_file',
                                             to='model_manager.configupload')),
            ],
            options={
                'db_table': 'archicad_eval_calculation_configs',
            },
        ),
    ]
