# Generated by Django 5.1.3 on 2025-01-03 10:18

import django.db.models.deletion
import model_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_manager', '0004_alter_calculationconfig_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configupload',
            name='document',
            field=models.FileField(upload_to=model_manager.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='configupload',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
