# Generated by Django 5.1.3 on 2025-01-04 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_manager', '0005_alter_configupload_document_alter_configupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
