# Generated by Django 5.1.4 on 2024-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialproperties",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
