# Generated by Django 5.1.3 on 2025-01-02 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_manager', '0003_configupload_calculationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configupload',
            name='document',
            field=models.FileField(upload_to='configs/'),
        ),
    ]
