# Generated by Django 5.1.3 on 2025-01-19 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0006_alter_configupload_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialproperties',
            old_name='ap_ml',
            new_name='ap_ml_a1_a3',
        ),
        migrations.RenameField(
            model_name='materialproperties',
            old_name='gwp_ml',
            new_name='gwp_ml_a1_a3',
        ),
        migrations.RenameField(
            model_name='materialproperties',
            old_name='penrt_ml',
            new_name='penrt_ml_a1_a3',
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='ap_ml_a1_a3_b4',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='ap_ml_lz',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='gwp_ml_a1_a3_b4',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='gwp_ml_lz',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='penrt_ml_a1_a3_b4',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='materialproperties',
            name='penrt_ml_lz',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
