# Generated by Django 6.0.6 on 2026-07-28 05:47

import django.core.validators
import model_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_manager", "0007_rename_ap_ml_materialproperties_ap_ml_a1_a3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingmetrics",
            name="annual_electricity_kwh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="annual_natural_gas_kwh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="annual_site_energy_kwh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_assumptions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_simulated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_status",
            field=models.CharField(
                choices=[
                    ("not_run", "Not run"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="not_run",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_use_intensity_kwh_m2_year",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="energy_weather_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="fassaden_oeffnungsflaeche",
            field=models.FloatField(default=0.0, verbose_name="Facade Opening Area"),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="fassaden_oeffnungsflaeche_unit",
            field=models.CharField(default="m2", max_length=10),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="fassaden_opake_flaeche",
            field=models.FloatField(default=0.0, verbose_name="Opaque Facade Area"),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="fassaden_opake_flaeche_unit",
            field=models.CharField(default="m2", max_length=10),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="fenster_wand_verhaeltnis",
            field=models.FloatField(
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Window-to-Wall Ratio",
            ),
        ),
        migrations.AddField(
            model_name="buildingmetrics",
            name="openstudio_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="weather_file",
            field=models.FileField(
                blank=True,
                help_text="Optional EnergyPlus Weather (EPW) file for energy simulation.",
                null=True,
                upload_to=model_manager.models.user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("epw",)
                    )
                ],
            ),
        ),
    ]
