# Generated by Django 6.0.6 on 2026-07-28 09:05

import django.core.validators
import model_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_manager", "0009_move_epw_uploads_to_user_library"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configupload",
            name="document",
            field=models.FileField(
                upload_to=model_manager.models.user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("csv", "xlsx")
                    ),
                    model_manager.models.validate_config_upload_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="document",
            field=models.FileField(
                upload_to=model_manager.models.user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("ifc",)
                    ),
                    model_manager.models.validate_model_upload_size,
                ],
            ),
        ),
    ]
