use super::*;

fn bytes(source: &str) -> Vec<u8> {
    source.as_bytes().to_vec()
}

fn minimal_document() -> Vec<u8> {
    bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "FILE_DESCRIPTION((''),'2;1');\n",
        "ENDSEC;\n",
        "DATA;\n",
        "ENDSEC;\n",
        "END-ISO-10303-21;\n",
    ))
}

// ---- Loading a fresh document through the ABI -------------------------

fn load(doc: &[u8]) -> i32 {
    let ptr = ifc_input_reserve(doc.len() as u32);
    if ptr == usize::MAX {
        return STATE.with(|state| -state.borrow().last_error);
    }
    unsafe {
        std::ptr::copy_nonoverlapping(doc.as_ptr(), ptr as *mut u8, doc.len());
    }
    ifc_load(doc.len() as u32)
}

fn write_value(value: &str) -> u32 {
    let bytes = value.as_bytes();
    let ptr = ifc_input_reserve(bytes.len() as u32);
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr as *mut u8, bytes.len());
    }
    bytes.len() as u32
}

fn read_output(len: usize) -> Vec<u8> {
    let ptr = ifc_output_ptr();
    let mut buffer = vec![0u8; len];
    unsafe {
        std::ptr::copy_nonoverlapping(ptr as *const u8, buffer.as_mut_ptr(), len);
    }
    buffer
}

#[test]
fn parses_a_minimal_valid_document() {
    let doc = minimal_document();
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_count(), 0);
}

#[test]
fn oversized_reservation_is_rejected_before_allocation_and_preserves_state() {
    let doc = minimal_document();
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_input_reserve(u32::MAX), usize::MAX);
    STATE.with(|state| {
        let state = state.borrow();
        assert_eq!(state.input, doc);
        assert_eq!(state.last_error, ErrorCode::TooLarge.code());
    });
    let len = ifc_serialize();
    assert_eq!(read_output(len as usize), doc);
}

#[test]
fn parses_typical_header_metadata_without_indexing_it() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "FILE_DESCRIPTION((''),'2;1');\n",
        "FILE_NAME('demo.ifc','2024-01-01',('author'),('org'),'app','app','');\n",
        "FILE_SCHEMA(('IFC4'));\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCPROJECT('guid',$,'Demo',$,$,$,$,$,$);\n",
        "ENDSEC;\n",
        "END-ISO-10303-21;\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_count(), 1);
}

#[test]
fn indexes_every_editable_attribute_kind() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCWALL('name',42,.T.,#2,$,*);\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_count(), 1);
    assert_eq!(ifc_entity_id(0), 1);
    assert_eq!(ifc_entity_attribute_count(0), 6);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 1); // quoted string
    assert_eq!(ifc_entity_attribute_kind(0, 1), 2); // number
    assert_eq!(ifc_entity_attribute_kind(0, 2), 3); // enum/logical
    assert_eq!(ifc_entity_attribute_kind(0, 3), 4); // reference
    assert_eq!(ifc_entity_attribute_kind(0, 4), 5); // $
    assert_eq!(ifc_entity_attribute_kind(0, 5), 5); // *
}

#[test]
fn lists_and_wrapped_values_are_visible_but_read_only() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCWALL((1,2,3),IFCLABEL('x'));\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 1), 0);
    assert_eq!(ifc_update_attribute(0, 0, write_value("$")), -4); // read-only
}

// ---- Byte-for-byte fidelity --------------------------------------------

#[test]
fn serialize_without_edits_is_byte_identical() {
    let doc = minimal_document();
    assert_eq!(load(&doc), 0);
    let len = ifc_serialize();
    assert!(len >= 0);
    assert_eq!(read_output(len as usize), doc);
}

#[test]
fn escaped_apostrophes_round_trip_inside_strings() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCWALL('it''s a wall');\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 1);
    let len = ifc_entity_attribute(0, 0);
    assert_eq!(read_output(len as usize), bytes("'it''s a wall'"));
}

#[test]
fn multiline_entities_comments_and_crlf_are_supported() {
    let doc = bytes(concat!(
        "ISO-10303-21;\r\n",
        "/* generated by test */\r\n",
        "HEADER;\r\n",
        "ENDSEC;\r\n",
        "DATA;\r\n",
        "#1=IFCWALL(\r\n",
        "  'multi',\r\n",
        "  /* a comment inside the call */\r\n",
        "  42\r\n",
        ");\r\n",
        "ENDSEC;\r\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_count(), 1);
    assert_eq!(ifc_entity_attribute_count(0), 2);
    let len = ifc_serialize();
    assert_eq!(read_output(len as usize), doc);
}

#[test]
fn empty_data_section_has_no_entities() {
    let doc = minimal_document();
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_entity_count(), 0);
    assert_eq!(ifc_find_entity(1), -3); // not found
}

// ---- Rejections ---------------------------------------------------------

#[test]
fn rejects_missing_iso_marker() {
    let doc = bytes("HEADER;\nENDSEC;\nDATA;\nENDSEC;\n");
    assert_eq!(load(&doc), -9);
}

#[test]
fn rejects_out_of_order_sections() {
    let doc = bytes("ISO-10303-21;\nDATA;\nENDSEC;\nHEADER;\nENDSEC;\n");
    assert_eq!(load(&doc), -9);
}

#[test]
fn rejects_unterminated_string() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL('oops);\nENDSEC;\n");
    assert_eq!(load(&doc), -10);
}

#[test]
fn rejects_unterminated_comment() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n/* never closed\nENDSEC;\n");
    assert_eq!(load(&doc), -11);
}

#[test]
fn rejects_unbalanced_parens() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL(('x');\nENDSEC;\n");
    assert_eq!(load(&doc), -12);
}

#[test]
fn rejects_missing_entity_id() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#=IFCWALL('x');\nENDSEC;\n");
    assert_eq!(load(&doc), -14);
}

#[test]
fn rejects_non_numeric_entity_id() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#ab=IFCWALL('x');\nENDSEC;\n");
    assert_eq!(load(&doc), -15);
}

#[test]
fn rejects_entity_id_out_of_u32_range() {
    let doc =
        bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#99999999999=IFCWALL('x');\nENDSEC;\n");
    assert_eq!(load(&doc), -16);
}

#[test]
fn rejects_duplicate_entity_ids() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCWALL('a');\n",
        "#1=IFCWALL('b');\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), -13);
}

#[test]
fn rejects_truncated_statement() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL('a')\nENDSEC;\n");
    assert_eq!(load(&doc), -17);
}

#[test]
fn rejects_documents_over_the_size_limit() {
    let mut doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL('");
    doc.extend(std::iter::repeat_n(b'a', 33 * 1024 * 1024));
    doc.extend_from_slice(b"');\nENDSEC;\n");
    assert_eq!(load(&doc), -6);
}

#[test]
fn rejects_too_many_entities() {
    let mut doc = String::from("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n");
    for i in 1..=100_001u32 {
        doc.push_str(&format!("#{i}=IFCWALL($);\n"));
    }
    doc.push_str("ENDSEC;\n");
    assert_eq!(load(doc.as_bytes()), -7);
}

#[test]
fn rejects_excessive_nesting() {
    let mut doc = String::from("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL(");
    for _ in 0..65 {
        doc.push('(');
    }
    for _ in 0..65 {
        doc.push(')');
    }
    doc.push_str(");\nENDSEC;\n");
    assert_eq!(load(doc.as_bytes()), -8);
}

// ---- Editing --------------------------------------------------------------

#[test]
fn every_editable_kind_can_be_updated() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#1=IFCWALL('name',42,.T.,#2,$,*);\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), 0);

    assert_eq!(ifc_update_attribute(0, 0, write_value("'new name'")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 1);

    assert_eq!(ifc_update_attribute(0, 1, write_value("3.5")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 1), 2);

    assert_eq!(ifc_update_attribute(0, 2, write_value(".F.")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 2), 3);

    assert_eq!(ifc_update_attribute(0, 3, write_value("#9")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 3), 4);

    assert_eq!(ifc_update_attribute(0, 4, write_value("*")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 4), 5);

    assert_eq!(ifc_update_attribute(0, 5, write_value("$")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 5), 5);
}

#[test]
fn update_permits_switching_kind() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL(42);\nENDSEC;\n");
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_update_attribute(0, 0, write_value("'now a string'")), 0);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 1);
}

#[test]
fn update_rejects_top_level_semicolon_and_comma() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL(42);\nENDSEC;\n");
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_update_attribute(0, 0, write_value("1;DROP")), -5);
    assert_eq!(ifc_update_attribute(0, 0, write_value("1,2")), -5);
}

#[test]
fn failed_update_rolls_back_to_the_previous_document() {
    let doc = bytes("ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\n#1=IFCWALL(42);\nENDSEC;\n");
    assert_eq!(load(&doc), 0);
    assert_eq!(
        ifc_update_attribute(0, 0, write_value("'unterminated)")),
        -5
    );
    let len = ifc_serialize();
    assert_eq!(read_output(len as usize), doc);
    assert_eq!(ifc_entity_attribute_kind(0, 0), 2);
}

#[test]
fn find_entity_locates_by_id() {
    let doc = bytes(concat!(
        "ISO-10303-21;\n",
        "HEADER;\n",
        "ENDSEC;\n",
        "DATA;\n",
        "#5=IFCWALL($);\n",
        "#7=IFCWALL($);\n",
        "ENDSEC;\n",
    ));
    assert_eq!(load(&doc), 0);
    assert_eq!(ifc_find_entity(7), 1);
    assert_eq!(ifc_find_entity(5), 0);
    assert_eq!(ifc_find_entity(999), -3);
}

#[test]
fn last_error_reflects_the_most_recent_failure() {
    let doc = bytes("HEADER;\n");
    assert_eq!(load(&doc), -9);
    assert_eq!(ifc_last_error(), 9);
}
